// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const fs = require('fs')
const vars = {}
for (let i = 0; i < 1; i++) {
  describe('Testiranje cnn spletne strani.', function () {
    this.timeout(30000)
    let driver 
  
    beforeEach(async function () {
      driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:9515').build()

    })
    afterEach(async function () {
      await driver.quit();
    })
    it('Testiranje glavne strani.', async function () {
      await driver.get("https://edition.cnn.com/")
      vars["main_h1"] = await driver.findElement(By.xpath("//section[@id=\'intl_homepage1-zone-1\']/div[2]/div/div/ul/li/article/a/h2")).getText()
      vars["main_h2"] = await driver.findElement(By.xpath("//section[@id=\'intl_homepage1-zone-1\']/div[2]/div/div[2]/ul/li/article/div/div[2]/h3/a/span[2]")).getText()
      vars["main_h3"] = await driver.findElement(By.css(".column:nth-child(3) li:nth-child(1) .cd__headline-text")).getText()
      vars["main_h4"] = await driver.findElement(By.css(".cn__listitem:nth-child(2) .cd__headline-text")).getText()
      vars["mainbuzz_h5"] = await driver.findElement(By.css("#intl_homepage1-zone-2 .column:nth-child(1) .cd__content:nth-child(2) .cd__headline-text:nth-child(2)")).getText()
      vars["glavna"] = "/----------------------------------------------";
      //cannot find video slide element
      // {
      //   const elements = await driver.findElements(By.id("anim16506072611c5"))
      //   assert(elements.length)
      // }
      {
        const elements = await driver.findElements(By.css(".cn__listitem:nth-child(1) .media__image"))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.css(".cn__listitem:nth-child(2) .media__image"))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.css(".column:nth-child(3) li:nth-child(1) .media__image"))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.xpath("//div[5]/div/div/ul/li/article/div/div/a/img"))
        assert(elements.length)
      }
      fs.truncate('./data.txt', 0, function () { console.log('deleted data.txt') })
    })


    it('Testiranje world strani.', async function () {
      // Test name: edition.cnn.com/world
      // Step # | name | target | value
      // 1 | open | https://edition.cnn.com/world | 
      await driver.get("https://edition.cnn.com/world")
      // 2 | storeText | css=.l-container:nth-child(2) > .zn__containers:nth-child(1) .cd__content:nth-child(2) .cd__headline-text:nth-child(1) | world_h1
      vars["world_h1"] = await driver.findElement(By.css(".l-container:nth-child(2) > .zn__containers:nth-child(1) .cd__content:nth-child(2) .cd__headline-text:nth-child(1)")).getText()
      // 3 | storeText | css=.l-container:nth-child(2) > .zn__containers:nth-child(1) li:nth-child(3) .cd__headline-text:nth-child(1) | world_h2
      vars["world_h2"] = await driver.findElement(By.css(".l-container:nth-child(2) > .zn__containers:nth-child(1) li:nth-child(3) .cd__headline-text:nth-child(1)")).getText()
      // 4 | storeText | css=.l-container:nth-child(2) > .zn__containers:nth-child(1) li:nth-child(4) .cd__headline-text:nth-child(1) | world_h3
      vars["world_h3"] = await driver.findElement(By.css(".l-container:nth-child(2) > .zn__containers:nth-child(1) li:nth-child(4) .cd__headline-text:nth-child(1)")).getText()
      // 5 | storeText | css=.l-container:nth-child(2) li:nth-child(5) .cd__headline-text:nth-child(1) | world_h4
      vars["world_h4"] = await driver.findElement(By.css(".l-container:nth-child(2) li:nth-child(5) .cd__headline-text:nth-child(1)")).getText()
      // 6 | storeText | css=#DIV_16509087397140 .column:nth-child(1) .cd__content:nth-child(2) .cd__headline-text:nth-child(1) | world_h5
      vars["world_h5"] = await driver.findElement(By.xpath("//div[2]/div/ul/li/article/div/div[2]/h3/a/span")).getText()
      // 7 | storeText | css=.cn:nth-child(3) .cd__content:nth-child(2) .cd__headline-text | world_h6
      vars["world_h6"] = await driver.findElement(By.css(".cn:nth-child(3) .cd__content:nth-child(2) .cd__headline-text")).getText()
      // 8 | storeText | css=#DIV_16509087397140 .zn-header__text | world_h7
      vars["world_h7"] = await driver.findElement(By.xpath("//div/h2")).getText()
      // 9 | assertElementPresent | css=.l-container:nth-child(2) > .zn__containers:nth-child(1) .media__image:nth-child(1) | 
      vars["world"] = "/----------------------------------------------";
      {
        const elements = await driver.findElements(By.css(".l-container:nth-child(2) > .zn__containers:nth-child(1) .media__image:nth-child(1)"))
        assert(elements.length)
      }
      // 10 | assertElementPresent | css=#DIV_16509087397140 .column:nth-child(1) .media__image | 
      {
        const elements = await driver.findElements(By.xpath("//div[2]/div/ul/li/article/div/div/a/img"))
        assert(elements.length)
      }
      // 11 | assertElementPresent | css=.cn:nth-child(3) .media__image | 
      {
        const elements = await driver.findElements(By.css(".cn:nth-child(3) .media__image"))
        assert(elements.length)
      }
    })
    it('Testiranje /africa strani.', async function () {
      await driver.get("https://edition.cnn.com/africa")
      vars["africa_h1"] = await driver.findElement(By.css("li:nth-child(1) .cd__headline-text")).getText()
      vars["africa_h2"] = await driver.findElement(By.css(".cd--idx-0 .cd__content:nth-child(1) .cd__headline-text")).getText()
      vars["afirca_h3"] = await driver.findElement(By.css(".zn__containers:nth-child(1) > .column:nth-child(1) li:nth-child(3) .cd__headline-text:nth-child(1)")).getText()
      vars["africa_h4"] = await driver.findElement(By.css(".zn__containers:nth-child(1) > .column:nth-child(1) li:nth-child(4) .cd__headline-text:nth-child(1)")).getText()
      vars["africa_h5"] = await driver.findElement(By.css(".cn:nth-child(1) > li:nth-child(5) .cd__headline-text")).getText()
      vars["africa_h6"] = await driver.findElement(By.css(".cn:nth-child(1) > li:nth-child(6) .cd__headline-text")).getText()
      vars["africa_h7"] = await driver.findElement(By.css(".cn:nth-child(3) > li:nth-child(2) .cd__headline-text")).getText()
      vars["africa_h8"] = await driver.findElement(By.css(".zn__containers:nth-child(1) > .column:nth-child(4) .cd__content:nth-child(2) .cd__headline-text:nth-child(1)")).getText()
      vars["africa"] = "/----------------------------------------------";
      {
        const elements = await driver.findElements(By.css("li:nth-child(1) .media__image"))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.css(".cn:nth-child(3) .media__image"))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.css(".zn__containers:nth-child(1) > .column:nth-child(4) .media__image"))
        assert(elements.length)
      }
    })
    it('Testiranje /americas strani.', async function () {
      await driver.get("https://edition.cnn.com/americas")
      vars["americas_h1"] = await driver.findElement(By.css("li:nth-child(1) .cd__headline-text")).getText()
      vars["americas_h2"] = await driver.findElement(By.css(".cn:nth-child(1) > li:nth-child(2) .cd__content:nth-child(1) .cd__headline-text")).getText()
      vars["americas_h3"] = await driver.findElement(By.css(".cn:nth-child(1) > li:nth-child(3) .cd__headline-text")).getText()
      vars["americas_h4"] = await driver.findElement(By.css(".cn:nth-child(1) > li:nth-child(4) .cd__headline-text")).getText()
      vars["americas_h5"] = await driver.findElement(By.css(".cn:nth-child(1) > li:nth-child(5) .cd__headline-text")).getText()
      vars["americas_h6"] = await driver.findElement(By.css(".cn:nth-child(1) > li:nth-child(6) .cd__headline-text")).getText()
      vars["americas_h7"] = await driver.findElement(By.css(".cd--idx-5 .cd__headline-text")).getText()
      vars["americas_h8"] = await driver.findElement(By.css(".cd--idx-6 .cd__headline-text")).getText()
      vars["americas_h9"] = await driver.findElement(By.css(".column:nth-child(4) .cd__headline-text")).getText()
      vars["americas_h10"] = await driver.findElement(By.css(".column:nth-child(5) .cd__headline-text")).getText()
      vars["americas"] = "/----------------------------------------------";
      {
        const elements = await driver.findElements(By.xpath("//img"))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.css(".column:nth-child(4) .media__image"))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.css(".column:nth-child(5) .media__image"))
        assert(elements.length)
      }
    })
    it('Testiranje /asia strani.', async function () {
      await driver.get("https://edition.cnn.com/asia")
      vars["asia_h1"] = await driver.findElement(By.css("li:nth-child(1) .cd__headline-text")).getText()
      vars["asia_h2"] = await driver.findElement(By.css(".cn__column:nth-child(2) .cd__headline-text")).getText()
      vars["asia_h3"] = await driver.findElement(By.css(".cn__column:nth-child(3) .cd__headline-text")).getText()
      vars["asia_h4"] = await driver.findElement(By.css(".cn__column:nth-child(4) .cd__headline-text")).getText()
      vars["asia_h5"] = await driver.findElement(By.css(".cn__column:nth-child(5) .cd__headline-text")).getText()
      vars["asia_h6"] = await driver.findElement(By.css(".zn__containers:nth-child(1) > .column:nth-child(1) li:nth-child(2) .cd__headline-text:nth-child(1)")).getText()
      vars["asia_h7"] = await driver.findElement(By.css(".cn:nth-child(2) .cd__content:nth-child(2) .cd__headline-text")).getText()
      vars["asia"] = "/----------------------------------------------";
      {
        const elements = await driver.findElements(By.css("li:nth-child(1) .media__image"))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.css(".cn__column:nth-child(2) .media__image"))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.css(".cd--idx-1 .media__image"))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.css(".cd--idx-2 .media__image"))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.css(".cd--idx-3 .media__image"))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.css(".zn__containers:nth-child(1) > .column:nth-child(1) li:nth-child(2) .media__image"))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.css(".cn:nth-child(2) .media__image"))
        assert(elements.length)
      }
    })
    it('Testiranje /australia strani.', async function () {
      await driver.get("https://edition.cnn.com/australia")
      {
        const elements = await driver.findElements(By.css("li:nth-child(1) .media__image"))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.xpath(`//*[@id="australia-zone-3"]/div[2]/div/div[1]/ul/li[1]/article/div/div[1]/a/img`))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.css(".column:nth-child(2) .media__image"))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.css(".column:nth-child(3) .media__image"))
        assert(elements.length)
      }
      vars["aus_h1"] = await driver.findElement(By.css("li:nth-child(1) .cd__headline-text")).getText()
      vars["aus_h2"] = await driver.findElement(By.css(".column:nth-child(1) li:nth-child(2) .cd__headline-text")).getText()
      vars["aus_h3"] = await driver.findElement(By.css(".column:nth-child(2) .cd__content:nth-child(2) .cd__headline-text")).getText()
      vars["aus_h4"] = await driver.findElement(By.css(".column:nth-child(3) li:nth-child(2) .cd__headline-text")).getText()
      vars["aus_h5"] = await driver.findElement(By.css(".cn__column:nth-child(2) .cd__headline-text")).getText()
      vars["aus_h6"] = await driver.findElement(By.css(".cn__column:nth-child(3) .cd__headline-text")).getText()
      vars["aus_h7"] = await driver.findElement(By.css(".cn__column:nth-child(4) .cd__headline-text")).getText()
      vars["aus_h8"] = await driver.findElement(By.css(".cn__column:nth-child(5) .cd__headline-text")).getText()
      vars["aus"] = "/----------------------------------------------";
    })
    it('Testiranje /politics strani.', async function () {
      await driver.get("https://edition.cnn.com/politics")
      vars["poli_h1"] = await driver.findElement(By.xpath("//h3/a/span")).getText()
      vars["poli_h2"] = await driver.findElement(By.xpath("//li[2]/article/div/div/h3/a/span")).getText()
      vars["poli_h3"] = await driver.findElement(By.xpath("//li[3]/article/div/div/h3/a/span")).getText()
      vars["poli_h4"] = await driver.findElement(By.xpath("//li[4]/article/div/div/h3/a/span")).getText()
      vars["poli_h5"] = await driver.findElement(By.xpath("//li[5]/article/div/div/h3/a/span")).getText()
      vars["poli_h6"] = await driver.findElement(By.css(".cn__listitem:nth-child(2) .cd__headline-text")).getText()
      vars["poli_h7"] = await driver.findElement(By.css(".cn__listitem:nth-child(3) .cd__headline-text")).getText()
      vars["poli"] = "/----------------------------------------------";
      {
        const elements = await driver.findElements(By.css(".zn__containers:nth-child(1) > .column:nth-child(1) .media__image"))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.css(".cn__listitem:nth-child(2) .media__image"))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.css(".cn__listitem:nth-child(3) .media__image"))
        assert(elements.length)
      }
    })
    it('Testiranje /business strani.', async function () {
      await driver.get("https://edition.cnn.com/business")
      vars["buiss_h1"] = await driver.findElement(By.css(".cd__wrapper:nth-child(2) > .cd__content a")).getText()
      vars["buiss_h2"] = await driver.findElement(By.css(".cn__listitem:nth-child(1) .cd__headline-text")).getText()
      vars["buiss_h3"] = await driver.findElement(By.css(".cn:nth-child(2) > .cn__listitem:nth-child(2) .cd__headline-text")).getText()
      vars["buiss_h5"] = await driver.findElement(By.xpath("//div[6]/div/div[2]/ul/li/article/div/div[2]/h3/a/span")).getText()
      vars["buiss_h4"] = await driver.findElement(By.xpath("//div[6]/div/div/ul/li/article/div/div[2]/h3/a/span")).getText()
      vars["buiss"] = "/----------------------------------------------";
      {
        const elements = await driver.findElements(By.css(".cd__wrapper:nth-child(2) .media__image"))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.css(".cn__listitem:nth-child(1) .media__image"))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.css(".cn:nth-child(2) > .cn__listitem:nth-child(2) .media__image"))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.xpath("//li[3]/article/div/div/a/img"))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.xpath("//div[6]/div/div/ul/li/article/div/div/a/img"))
        assert(elements.length)
      }
      {
        const elements = await driver.findElements(By.xpath("//div[6]/div/div[2]/ul/li/article/div/div/a/img"))
        assert(elements.length)
      }
    })
    it('Testiranje /health strani.', async function () {
      await driver.get("https://edition.cnn.com/health")
      {
        const elements = await driver.findElements(By.css(".cn:nth-child(1) > li .media__image"))
        assert(elements.length)
      }
      vars["health_h1"] = await driver.findElement(By.css(".cn:nth-child(1) > li:nth-child(1) .cd__headline-text")).getText()
      vars["health_h2"] = await driver.findElement(By.css(".l-container:nth-child(2) .column:nth-child(1) li:nth-child(2) .cd__headline-text:nth-child(1)")).getText()
      vars["health_h3"] = await driver.findElement(By.css(".l-container:nth-child(2) .column:nth-child(1) li:nth-child(3) .cd__headline-text:nth-child(1)")).getText()
      vars["health_h4"] = await driver.findElement(By.css(".l-container:nth-child(2) .column:nth-child(1) li:nth-child(4) .cd__headline-text:nth-child(1)")).getText()
      vars["health_h5"] = await driver.findElement(By.css(".l-container:nth-child(2) .column:nth-child(1) li:nth-child(5) .cd__headline-text:nth-child(1)")).getText()
      vars["health"] = "/----------------------------------------------";
    })

    it('Test shranjenih spremenljivk.', async function () {
     
      for(let key in vars){
        
        assert(vars[key].length > 5, key);
  
      }
  
    })

    it("Pisanje spremenljivk v datoteko.", () => {

      for (let Var in vars) {
        //write to .txt file

        fs.writeFileSync('./data.txt', Var + " " + vars[Var] + "\n",
          {
            encoding: "utf8",
            flag: "a+",
            mode: 0o666
          }

        );

        //write to .json file
        fs.writeFile("./data.json", JSON.stringify(vars, null, 4), function (err) {
          if (err) {
            console.log(err + " saving error");
          }
        });




      }


    })

  })
}