// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const { doesNotMatch } = require('assert')

describe('CnnSearch_test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:9515').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CnnSearch_test', async function() {
    await driver.get("https://edition.cnn.com/")
    driver.manage().setTimeouts({ implicit: 2000, pageLoad: 5000, script: 1000 });
    vars["search_word"] = "elections"
    
    await driver.findElement(By.xpath("//div[@id='onetrust-button-group']/button")).click()
    await driver.findElement(By.css(`.sc-bdVaJa > .search-icon`)).click()
    await driver.findElement(By.xpath(`//*[@id="header-search-bar"]`)).sendKeys(vars["search_word"])
    await driver.findElement(By.xpath("//button/div")).click()
    await driver.findElement(By.linkText("Emmanuel Macron wins France\'s presidential election")).click()
    await driver.findElement(By.xpath(`//section[@id="body-text"]//div[contains(text(), vars["search_word"])]`))
    
    
  })
})
