// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')



for (let i = 0; i < 1; i++) {
  describe('anketa_zadruga', function () {

    this.timeout(30000)
    let driver
    let vars
    beforeEach(async function () {
      driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:9515').build()
      driver.manage().deleteAllCookies();
      vars = {}
    })
    afterEach(async function () {
      await driver.quit();
    })
    it('anketa', async function () {
      // Test name: anketa
      // Step # | name | target | value
      // 1 | open | /rijaliti/anketa-pobednik-zadruga-4-puls-online/kqq893l | 
      await driver.get("https://www.pulsonline.rs/rijaliti/anketa-pobednik-zadruga-4-puls-online/kqq893l")
      driver.manage().setTimeouts({ implicit: 3000, pageLoad: 5000, script: 1000 });
      // 2 | mouseOver | id=cmpbntyestxt | 

      await driver.findElement(By.id("cmpbntyestxt")).click()

      // 4 | click | css=.poll-item:nth-child(2) > label | 
      await driver.findElement(By.css(".poll-item:nth-child(2) > label")).click()
      // 5 | click | css=.poll-item:nth-child(23) > input | 
      await driver.findElement(By.css(".poll-item:nth-child(23) > input")).click()
      await driver.executeScript("window.scrollTo(0,1040)")
       // 6 | assertElementPresent | css=.poll > h3 | 
    {
      const elements = await driver.findElements(By.css(".poll > h3"))
      assert(elements.length)
    }
    })
  })
}
