// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
require('dotenv').config()


for (let i = 0; i < 1; i++) {
  describe('login', function () {
    this.timeout(30000)
    let driver
    let vars
    beforeEach(async function () {
      driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:9515').build()
      vars = {}


    })
    afterEach(async function () {
      await driver.quit();
    })
    it('login', async function () {
      vars["username"] = process.env.cnnuser
      vars["password"] = process.env.cnngeslo
      // Test name: login
      // Step # | name | target | value
      // 1 | open | / | 
      await driver.get("https://edition.cnn.com/")
      driver.manage().setTimeouts({ implicit: 3000, pageLoad: 5000, script: 1000 });
      await driver.findElement(By.xpath("//div[@id='onetrust-button-group']/button")).click()

      // 2 | click | css=.indexes__ButtonContainer-oqeuru-1 > .Text-sc-1amvtpj-0-span | 
      await driver.findElement(By.css(".indexes__ButtonContainer-oqeuru-1 > .Text-sc-1amvtpj-0-span")).click()
      // 3 | type | id=login-email-input | korbar41@gmail.com
      await driver.findElement(By.id("login-email-input")).sendKeys(vars["username"])
      // 4 | type | id=login-password-input | ECW9Yb8yH@bq4JT
      await driver.findElement(By.id("login-password-input")).sendKeys(vars["password"])
      // 5 | click | id=login-email-input | 
      await driver.findElement(By.id("login-email-input")).click()
      // 6 | click | css=.user-account-shared-page | 
      await driver.findElement(By.css(".user-account-shared-page")).click()
      // 7 | click | css=.user-account-shared__wrapper | 
      await driver.findElement(By.css(".user-account-shared__wrapper")).click()
      // 8 | click | css=.user-account-login-form__button | 
      await driver.findElement(By.css(".user-account-login-form__button")).click()
    })
  })


}

